version: '3.8'

services:
  # Servicio MongoDB
  mongo:
    image: mongo:latest
    container_name: habit-tracker-mongo
    restart: always
    ports:
      # <PUERTO_LOCAL>:<PUERTO_CONTENEDOR_MONGO>
      - "27017:27017" 
    environment:
    # Inicializar el administrador de MongoDB
      MONGO_INITDB_ROOT_USERNAME: ${DB_DEFAULT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_DEFAULT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DEFAULT_NAME}
    volumes:
      # Persistencia de datos: Guarda los datos fuera del contenedor para que no se pierdan
      - mongo-data:/data/db
      
  # Flask App
  app:
    build:
      context: .. 
      dockerfile: ./docker/Dockerfile
    container_name: habit-tracker-app
    ports:
      - "5000:5000"   # <PUERTO_LOCAL>:<PUERTO_CONTENEDOR_FLASK>
    depends_on:
      - mongo   # Asegurar MongoDB inicie antes que la app
    env_file:
      - ../.env
    environment:
      # Inyectar variables esenciales al contenedor
      DB_DEFAULT_HOST: ${DB_DEFAULT_HOST}
      DB_DEFAULT_USER: ${DB_DEFAULT_USER}
      DB_DEFAULT_PASSWORD: ${DB_DEFAULT_PASSWORD}
      FLASK_ENV: ${ENV_DEFAULT}
      APP_SECRET_KEY: ${APP_SECRET_KEY}
    
volumes:
  mongo-data: # Define el volumen persistente para la DB